---
- name: Deploy .dotfiles on Arch Linux
  hosts: all

  tasks:
    - name: Allow passwordless pacman for wheel group
      ansible.builtin.copy:
        content: "%wheel ALL=(ALL) NOPASSWD: /usr/bin/pacman\n"
        dest: /etc/sudoers.d/10-pacman-nopasswd
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -csf %s
      become: yes

    - name: Install Pacman packages
      community.general.pacman:
        name:
          - base-devel
          - docker
          - file
          - go
          - keepassxc
          - kitty
          - nvm
          - procps-ng
          - ttf-victor-mono-nerd
          - vivaldi
          - zsh
        state: present
        update_cache: yes
      become: true

    - name: Check if yay is already installed
      ansible.builtin.command: which yay
      register: yay_check
      failed_when: false
      changed_when: false

    - name: Download and install yay package manager
      block:
        - name: Clone yay from AUR
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay

        - name: Build and install yay
          ansible.builtin.command:
            cmd: makepkg -si --noconfirm
            chdir: /tmp/yay
      when: yay_check.rc != 0

    - name: Install AUR packages
      kewlfft.aur.aur:
        use: yay
        name:
          - devpod-bin
        state: present
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        PKG_CONFIG_PATH: "/usr/lib/pkgconfig:/usr/share/pkgconfig"
        VIRTUAL_ENV: ""
        HOMEBREW_PREFIX: ""
        HOMEBREW_CELLAR: ""
        HOMEBREW_REPOSITORY: ""
        LD_LIBRARY_PATH: ""

    - name: Clone .dotfiles repository
      ansible.builtin.git:
        repo: https://github.com/Dapacruz/.dotfiles.git
        dest: ~/.dotfiles
        clone: yes
        update: no

    - name: Check if Oh My Zsh is installed
      ansible.builtin.stat:
        path: ~/.oh-my-zsh
      register: ohmyzsh

    - name: Install Oh My Zsh
      block:
        - name: Download Oh My Zsh installation script
          get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: /tmp/install_ohmyzsh.sh
            mode: '0755'
          become: false

        - name: Run Oh My Zsh installation script
          command: sh /tmp/install_ohmyzsh.sh --unattended
          become: false
          register: ohmyzsh_result
          failed_when: "'FAILED' in ohmyzsh_result.stderr"
      when: not ohmyzsh.stat.exists

    - name: Check if Homebrew is installed
      ansible.builtin.stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew

    - name: Install Homebrew
      block:
        - name: Create Homebrew parent directory
          ansible.builtin.file:
            path: /home/linuxbrew
            state: directory
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"
            mode: '0755'
          become: true

        - name: Create Homebrew install directory
          ansible.builtin.file:
            path: /home/linuxbrew/.linuxbrew
            state: directory
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"
            mode: '0755'
          become: true

        - name: Download Homebrew installation script
          get_url:
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            dest: /tmp/install_homebrew.sh
            mode: '0755'
          become: false

        - name: Run Homebrew installation script
          ansible.builtin.shell: NONINTERACTIVE=1 /tmp/install_homebrew.sh
          args:
            executable: /bin/bash
            creates: /home/linuxbrew/.linuxbrew/bin/brew
          become: false
          register: homebrew_result

        - name: Update .zshrc
          ansible.builtin.lineinfile:
            path: "{{ ansible_facts['user_dir'] }}/.zshrc"
            line: |

              eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      when: not homebrew.stat.exists

    - name: Add Homebrew zsh to /etc/shells if missing
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: /home/linuxbrew/.linuxbrew/bin/zsh
        state: present
        create: no
      become: true

    - name: Set default shell to Zsh
      user:
        name: "{{ ansible_facts['user_id'] }}"
        shell: /home/linuxbrew/.linuxbrew/bin/zsh
      become: true

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install Homebrew packages
      community.general.homebrew:
        state: present
        install_options:
          - formula
          - quiet
        name:
          - bat
          - bfg
          - cmatrix
          - dust
          - fd
          - fping
          - fzf
          - httpie
          - gcc
          - go
          - iftop
          - ipcalc
          - iperf3
          - jq
          - kubectl
          - lazygit
          - lsd
          - luarocks
          - mtr
          - neovim
          - netpbm
          - nload
          - nmap
          - nuttcp
          - procs
          - python@3.13
          - ripgrep
          - rust
          - sd
          - starship
          - stylua
          - tmux
          - tokei
          - tre-command
          - utf8proc
          - uv
          - wget
          - xmlstarlet
          - xq
          - yarn
          - yq
          - zoxide
          - zsh-vi-mode
          - zsh-syntax-highlighting

    - name: Check if Python venv dir exists
      ansible.builtin.stat:
        path: ~/venv
      register: venv

    - name: Create Python venv
      block:
        - name: Create Python venv dir
          ansible.builtin.file:
            path: ~/venv
            state: directory

        - name: Create Python venv
          ansible.builtin.shell: python3.13 -m venv ~/venv/3.13
          args:
            executable: /bin/bash
          register: python_result
          failed_when: "'FAILED' in python_result.stderr"
          become: false
      when: not venv.stat.exists

    - name: Stow dotfiles
      ansible.builtin.shell:
        cmd: ~/.dotfiles/arch/stow/stow.sh
        chdir: ~/.dotfiles/arch/stow

    - name: Clone Tmux TPM repository
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.config/tmux/plugins/tpm
        clone: yes
        update: yes

    - name: Install Node LTS via nvm
      ansible.builtin.shell: |
        source /usr/share/nvm/init-nvm.sh
        nvm install --lts
        nvm alias default 'lts/*'
      args:
        executable: /bin/bash

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        groups: docker
        append: yes
      become: yes

    - name: Set up Docker
      block:
        - name: Enable and start Docker service
          ansible.builtin.systemd:
            name: docker
            enabled: yes
            state: started
          become: yes

